### PR TITLE
ADGroup: Add support for managed service accounts

### LINKED ISSUE #532: ADGroup: Cannot set Standalone/Group Managed Service Account Members
#### Details of the scenario you tried and the problem that is occurring

We're using cross-forest service accounts, and we want to represent the configuration in PowerShell DSC. However, it looks like `msDS-GroupManagedServiceAccount` and `msDS-ManagedServiceAccount` are not supported in the `Add-ADCommonGroupMember` function in the ActiveDirectoryDsc.Common module.

#### Verbose logs showing the problem
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' =
MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SHASTALOCALDC with user sid S-1-5-21-3472425590-1118686215-1165301856-500.
VERBOSE: [SHASTALOCALDC]: LCM:  [ Start  Set      ]
VERBOSE: [SHASTALOCALDC]: LCM:  [ Start  Resource ]  [[ADGroup]dl1]
VERBOSE: [SHASTALOCALDC]: LCM:  [ Start  Test     ]  [[ADGroup]dl1]
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Retrieving group membership based on 'DistinguishedName' property. (ADG0001)
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Group membership is NOT in the desired state. (ADG0002)
VERBOSE: [SHASTALOCALDC]: LCM:  [ End    Test     ]  [[ADGroup]dl1]  in 0.1720 seconds.
VERBOSE: [SHASTALOCALDC]: LCM:  [ Start  Set      ]  [[ADGroup]dl1]
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Group membership objects are in '1' different AD Domains. (ADG0013)
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Retrieving group membership based on 'DistinguishedName' property. (ADG0001)
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Updating AD Group 'MallardPermissions'. (ADG0006)
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Retrieving group membership based on 'DistinguishedName' property. (ADG0001)
VERBOSE: [SHASTALOCALDC]:                            [[ADGroup]dl1] Adding '1' member(s) to AD group 'MallardPermissions'. (ADG0003)
Cannot validate argument on parameter 'Members'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.AddADGroupMember
    + PSComputerName        : localhost

VERBOSE: [SHASTALOCALDC]: LCM:  [ End    Set      ]  [[ADGroup]dl1]  in 1.1070 seconds.
The PowerShell DSC resource '[ADGroup]dl1' with SourceInfo 'C:\Users\Administrator\desktop\Test.ps1::31::9::ADGroup' threw one or more non-terminating errors while
running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [SHASTALOCALDC]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.984 seconds
```
#### Suggested solution to the issue
Add `msDS-GroupManagedServiceAccount` and `msDS-ManagedServiceAccount` object types to the `Add-ADCommonGroupMember` function in [ActiveDirectoryDsc.Common](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/6942331a80fa20fdb1c34fe104deca6c26f739d2/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1#L1485-L1500):

```powershell
...

if ($memberObjectClass -eq 'computer')
{
    $memberObject = Get-ADComputer @commonParameters
}
elseif ($memberObjectClass -eq 'group')
{
    $memberObject = Get-ADGroup @commonParameters
}
elseif ($memberObjectClass -eq 'user')
{
    $memberObject = Get-ADUser @commonParameters
}
elseif ($memberObjectClass -eq 'msDS-ManagedServiceAccount')
{
    $memberObject = Get-ADServiceAccount @commonParameters
}
elseif ($memberObjectClass -eq 'msDS-GroupManagedServiceAccount')
{
    $memberObject = Get-ADServiceAccount @commonParameters
}

...
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration ADGroup_NewGroupMultiDomainMembers_Config
{
    Import-DscResource -ModuleName ActiveDirectoryDsc

    node localhost
    {
        ADGroup 'dl1'
        {
            GroupName           = 'MallardPermissions'
            GroupScope          = 'DomainLocal'
            Path                = 'OU=Groups,OU=LocalDomain,DC=shasta,DC=local'
            MembershipAttribute = 'DistinguishedName'
            Members             = @(
                'CN=srv-mallard,CN=Managed Service Accounts,DC=shasta,DC=cloud'
            )
        }
    }
}
```

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
4.2.0.0

### PR DESCRIPTION
**Pull request by JohnCardenas**
#### Pull Request (PR) description
Adds support for `msDS-ManagedServiceAccount` and `msDS-GroupManagedServiceAccount` objects to the ADGroup resource by patching the `Add-ADCommonGroupMember` function of ActiveDirectoryDsc.Common.

#### This Pull Request (PR) fixes the following issues
- Fixes #532 

#### Task list

- [ ] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in resource directory README.md.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Conceptual help topic added/updated (cultureFolder\about_ResourceName.help.txt).
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/533)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Hi @JohnCardenas, are you still working on this PR, as it is in draft? Could you add some unit tests for the change?

**Comment by JohnCardenas** [comment]
Hi @X-Guardian,

Apologies, I've been dealing with several other issues that prevented me from paying attention to this. I'm rather unfamiliar with PowerShell unit testing. Where would you recommend I begin?

**Comment by X-Guardian** [comment]
Hi @JohnCardenas, no problem.

Regarding unit tests, have a read of the [Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines/) to familiarise yourself with the process. There are already unit tests for the `Add-ADCommonGroupMember` function in `tests\Unit\ActiveDirectoryDsc.Common.Tests.ps1`. You will see them in the `Describe 'ActiveDirectoryDsc.Common\Add-ADCommonGroupMember'` block. You just need to add a context or two for the new code you have introduced.

Unfortunately, since you raised this PR, the `ActiveDirectoryDsc` module has been converted to using a new Azure Devops based CI/CD process. This has meant major changes to the file structure of the module, so you are going to need to rebase your development branch and move your code changes into the new file location.

If you need help with any of this, message me on the PowerShell Slack channel: http://slack.poshcode.org.

**Comment by johlju** [comment]
Closing this as tis was merged in PR https://github.com/dsccommunity/ActiveDirectoryDsc/pull/578

**Pull request closed without merging**
