### PR TITLE
WaitForADDomain: Fix Find-DomainController handling of inner exception

### LINKED ISSUE #530: WaitADDomain: fails if DC not ready
#### Verbose logs showing the problem
```
[EC2AMAZ-0J01R66]: LCM:  [ Start  Resource ]  [[WaitForADDomain]ForestWait]
[EC2AMAZ-0J01R66]: LCM:  [ Start  Test     ]  [[WaitForADDomain]ForestWait]
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] Determining the current state of the 
Active Directory domain 'tf-tf.local'. (WFADD0013)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] Searching for a domain controller in the 
domain 'tf-tf.local'. (WFADD0001)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] Impersonating the credentials 
'tf-tf\xxxxxxxxx' when looking for a domain controller. (WFADD0011)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] Searching for a domain controller in the 
domain 'tf-tf.local'. (ADCOMMON0052)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] The type 
'System.DirectoryServices.ActiveDirectory.DirectoryContext' is already loaded into the PowerShell session. 
(ADCOMMON0043)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] Get a new Active Directory context of the 
type 'Domain'. (ADCOMMON0046)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] The Active Directory context will target 
'tf-tf.local'. (ADCOMMON0047)
[EC2AMAZ-0J01R66]:                            [[WaitForADDomain]ForestWait] The Active Directory context will be 
accessed using the 'tf-tf\xxxxxxxxx' credentials. (ADCOMMON0048)
[EC2AMAZ-0J01R66]: LCM:  [ End    Test     ]  [[WaitForADDomain]ForestWait]  in 4.8180 seconds.
PowerShell DSC resource MSFT_WaitForADDomain  failed to execute Test-TargetResource functionality with error message: 
Exception calling "FindOne" with "1" argument(s): "Domain controller not found in the domain "tf-tf.local"." 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
```
#### Suggested solution to the issue
Wait until the DC is ready

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

I create new server and wait for DC to become ready to join the domain. If the DC is ready, server joins the domain without problem, but if WaitForADDomain runs when DC is being configured, the resource fails. During the next consistency check the server joins the domain as the DC is ready by that time (also proving the configuration is hopefully correct).

```
        WaitForADDomain ForestWait
        {
            DomainName = $InternalDomain
            WaitTimeout = 900
            Credential = $default_creds
            DependsOn = "[DNSServerAddress]DNS"
            WaitForValidCredentials = $true
        }
```
#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```
#### Version and build of PowerShell the target node is running

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### Version of the DSC module that was used ('dev' if using current dev branch)
4.2.0.0

### PR DESCRIPTION
**Pull request by xpn**
#### Pull Request (PR) description

Fixes an issue within `Find-DomainController` when used by `WaitForADDomain` which caused an unhandled exception to be thrown when a domain controller was not yet available.

This was due to a check for a base exception of `System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException` which instead was being surfaced as an InnerException of `System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException`.

#### This Pull Request (PR) fixes the following issues

- Fixes #530 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/556)

### CODE REVIEW

**Comment by xpn** [comment]
As per #530 I've created this pull request (my first ever pull request on Github, so please let me know if anything is incorrect).

I did have a question around the cleanup of the existing check for `System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException`:

https://github.com/dsccommunity/ActiveDirectoryDsc/blob/5ea5a1300fcee61c447b6c544aab7c28a9339216/source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1#L2057

Should be now removed as part of this change, or if this was added to account for another potential exception which may be thrown?

**Comment by X-Guardian** [comment]
Congratulations on your first GitHub PR @xpn! I hope it will be the first of many.

 The checks are currently failing as you haven't added an entry to the CHANGELOG.md file. If you can do this, I'll then review the change.

**Comment by X-Guardian** [comment]
Please see https://github.com/dsccommunity/ActiveDirectoryDsc/issues/530#issuecomment-582304291 for an update on this.

**Comment by jcuzzi** [comment]
@xpn @X-Guardian Would love for this fix to go live so I don't have to manually edit the module on the image I use to get this working.

**Comment by X-Guardian** [comment]
Hi @jcuzzi, we still don't know the correct exception to check for. Please see the discussion in issue #530. If you can re-create the issue, please add the verbose messages to your module and let us know what exception you are getting.

**Comment by jcuzzi** [comment]
@X-Guardian, it seems that using the wrapper function is what causes the nested exception.  Take a look at the following snip and results:

```
function Find-DomainControllerFindOneWrapper
{
    [CmdletBinding()]
    [OutputType([System.DirectoryServices.ActiveDirectory.DomainController])]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.DirectoryServices.ActiveDirectory.DirectoryContext]
        $DirectoryContext
    )

    return [System.DirectoryServices.ActiveDirectory.DomainController]::FindOne($DirectoryContext)
}

Add-Type -AssemblyName 'System.DirectoryServices'

Write-Verbose -Message ($script:localizedData.NewDirectoryContext -f 'Domain') -Verbose

$newObjectArgumentList = @(
    'Domain'
)   
$newObjectArgumentList += @(
    'asdf.io'
)

$newObjectParameters = @{
    TypeName     = $typeName
    ArgumentList = $newObjectArgumentList
}

[System.DirectoryServices.ActiveDirectory.DirectoryContext]$adDirectoryContext = New-Object @newObjectParameters


try
{
    Write-Host "Using Wrapper:"
    $domainControllerObject = Find-DomainControllerFindOneWrapper -DirectoryContext $adDirectoryContext
}
catch [System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException]
{
    Write-Host 'Specific catch: ActiveDirectoryObjectNotFoundException'
    Write-Host 'Exception Name: ' + $_.Exception.GetType().FullName
}
catch [System.Management.Automation.MethodInvocationException]
{
    Write-Host 'Specific catch: MethodInvocationException'
    Write-Host 'Exception Name: ' + $_.Exception.GetType().FullName
    Write-Host 'Inner Exception Name: ' + $_.Exception.InnerException.GetType().FullName
} 
catch
{
    Write-Host 'Generic catch'
    Write-Host 'Exception Name: ' + $_.Exception.GetType().FullName
    Write-Host 'Inner Exception Name: ' + $_.Exception.InnerException.GetType().FullName
}

try
{
    Write-Host "Not using Wrapper:"
    $domainControllerObject = [System.DirectoryServices.ActiveDirectory.DomainController]::FindOne($adDirectoryContext)
}
catch [System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException]
{
    Write-Host 'Specific catch: ActiveDirectoryObjectNotFoundException'
    Write-Host 'Exception Name: ' + $_.Exception.GetType().FullName
}
catch [System.Management.Automation.MethodInvocationException]
{
    Write-Host 'Specific catch: MethodInvocationException'
    Write-Host 'Exception Name: ' + $_.Exception.GetType().FullName
    Write-Host 'Inner Exception Name: ' + $_.Exception.InnerException.GetType().FullName
} 
catch
{
    Write-Host 'Generic catch'
    Write-Host 'Exception Name: ' + $_.Exception.GetType().FullName
    Write-Host 'Inner Exception Name: ' + $_.Exception.InnerException.GetType().FullName
}
```

Using Wrapper:
Specific catch: MethodInvocationException
Exception Name:  + System.Management.Automation.MethodInvocationException
Inner Exception Name:  + System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException
Not using Wrapper:
Specific catch: ActiveDirectoryObjectNotFoundException
Exception Name:  + System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException

I don't see the purpose of the wrapper function since its only running a single return line and only used in one place.

**Comment by X-Guardian** [comment]
Hi @jcuzzi, the point of the wrapper function is so that it can be mocked within the unit tests.

We proved that a try/catch block will match on either the exception or the inner exception, so I don't think that is the issue. I still think we are hitting a different exception, we just need to know what one.

**Comment by jcuzzi** [comment]
Hi @X-Guardian.  This commit did resolve the issue for me: 20250c59f21226f21f60debe9a034e52dcaa8a91

I don't see any additional exceptions being thrown.

**Comment by X-Guardian** [comment]
Were you consistently getting the 'Domain Controller not Found' error though?

**Comment by jcuzzi** [comment]
Yes.  I use this module in combination with terraform to configure lab environments from scratch. Every client using the WaitForADDomain resource would run into this error because the domain does not exist until the PDC is configured.

I ended up manually editing the the module on my base image to include 20250c59f21226f21f60debe9a034e52dcaa8a91 which fixed the issue for me.

**Comment by X-Guardian** [comment]
OK, if you want to see it fixed permanently, please add the verbose messaging to an unmodified module as discussed in https://github.com/dsccommunity/ActiveDirectoryDsc/issues/530#issuecomment-582304291 and recreate the issue, then post the verbose logs to the issue.

**Comment by johlju** [comment]
@X-Guardian was this resolved by merged PR https://github.com/dsccommunity/ActiveDirectoryDsc/pull/577?

**Comment by X-Guardian** [comment]
Hi @johlju,

No, still need to re-work the `Find-DomainController` function exception handling.

**Comment by X-Guardian** [comment]
We still have the `ActiveDirectoryObjectNotFoundException` duplicated in this PR, but I'm not confident enough to remove the original catch, in case there is still a scenario which hits it. I'm therefore going to get this merged so it can be included in the 6.0 release.

**Pull request merged**
