### PR TITLE
ActiveDirectoryDsc: Pin All RequiredModules and Add 'Sampler.GitHubTasks'

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR pins the versions all the modules in `RequiredModules` to avoid build issues with breaking changes introduced by these modules.

It also adds the `Sampler.GitHubTasks` module which was an undocumented breaking change introduced by https://github.com/gaelcolas/Sampler/pull/240

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/663)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/663#-:-MdpUxIaAD5TCsfDNG0Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @X-Guardian)

**Comment by johlju** [comment]
FYI Gael made a blog here and was mentioned on of the DSC Community calls https://dsccommunity.org/blog/updating-sampler-github-tasks/

**Comment by X-Guardian** [comment]
Sampler claims to be using semver versioning, so the major version should have been bumped for this change. Also, you have a list of all the Dsc repos, so the creation of an issue in each one flagging this would have been very simple.

Please don't merge my PRs in future.

**Comment by johlju** [comment]
> Sampler claims to be using semver versioning, so the major version should have been bumped for this change.

Sampler has not yet gone to v1.0.0 so breaking changes does not automatically raise major. But I agree that at this point it it could go to v1.0.0 so breaking changes can be tracked by versioning. Suggest adding a issue to the Sampler repo so @gaelcolas can take that under consideration.

> Also, you have a list of all the Dsc repos, so the creation of an issue in each one flagging this would have been very simple.

Yeah, it would have been great but not as simple in practice - we are to few people with to little free time to do this for ~60 repos. Even with a tool that could create issues automatically it takes a while to set up and verify each time, so inform the community through blog posts and or community call is easier and faster. I think your above suggestion would have solved this better, having raised the major version, so it showed something major changed. 🙂 

> Please don't merge my PRs in future.

Okay, sure. Can I ask why? 🙂 I thought it would save you some time since I already was on the page.

**Pull request merged**
