### PR TITLE
ADGroup: Refactor Module, Unit and Integration Tests

### LINKED ISSUE #494: ADGroup: Seemingly removing members even if they are present in property Members
#### Details of the scenario you tried and the problem that is occurring
If a group already have one member 'Guest' and then the group should enforce two members 'Guest' and 'Administrator' it looks like in the verbose log that it actually removes the 'Guest' as member and the re-adds it.

#### Verbose logs showing the problem
```
    Context When using configuration MSFT_ADGroup_EnforceMembersGroup5_Config
WARNING: It is not recommended to use domain credential for node 'localhost'. In order to suppress the warning, you can add a property named 'PSDscAllowDomainUser' with a value of $true to your DSC configuration data for node 'localhost'.
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer DC01 with user sid S-1-5-21-530133819-3181352061-503517500-500.
VERBOSE: [DC01]: LCM:  [ Start  Set      ]
VERBOSE: [DC01]:                            [DSCEngine] Importing the module C:\source\ActiveDirectoryDsc\DscResources\MSFT_ADGroup\MSFT_ADGroup.psm1 in force mode.
VERBOSE: [DC01]: LCM:  [ Start  Resource ]  [[ADGroup]Integration_Test]
VERBOSE: [DC01]: LCM:  [ Start  Test     ]  [[ADGroup]Integration_Test]
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Importing the module MSFT_ADGroup in force mode.
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Retrieving group membership based on 'SamAccountName' property. (ADG0001)
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Group membership is NOT in the desired state. (ADG0002)
VERBOSE: [DC01]: LCM:  [ End    Test     ]  [[ADGroup]Integration_Test]  in 0.4530 seconds.
VERBOSE: [DC01]: LCM:  [ Start  Set      ]  [[ADGroup]Integration_Test]
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Importing the module MSFT_ADGroup in force mode.
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Updating AD Group 'DscDistributionGroup1'. (ADG0006)
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Retrieving group membership based on 'SamAccountName' property. (ADG0001)
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Removing '1' member(s) from AD group 'DscDistributionGroup1'. (ADG0004)
VERBOSE: [DC01]:                            [[ADGroup]Integration_Test] Adding '2' member(s) to AD group 'DscDistributionGroup1'. (ADG0003)
VERBOSE: [DC01]: LCM:  [ End    Set      ]  [[ADGroup]Integration_Test]  in 1.1410 seconds.
VERBOSE: [DC01]: LCM:  [ End    Resource ]  [[ADGroup]Integration_Test]
VERBOSE: [DC01]: LCM:  [ End    Set      ]
VERBOSE: [DC01]: LCM:  [ End    Set      ]    in  2.1880 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
```
#### Suggested solution to the issue
We should not remove members that are suppose to be members. We should only remove members not part of the `Members` property,

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
<#
    .SYNOPSIS
        Add and remove members from a group.
#>
Configuration MSFT_ADGroup_ModifyMembersGroup5_Config
{
    Import-DscResource -ModuleName 'ActiveDirectoryDsc'

    node $AllNodes.NodeName
    {
        ADGroup 'Integration_Test'
        {
            GroupName        = $Node.Group5_Name
            MembersToInclude = @(
                'Guest'
            )
            MembersToExclude = @(
                'Administrator'
            )

            Credential       = New-Object `
                -TypeName System.Management.Automation.PSCredential `
                -ArgumentList @(
                $Node.AdministratorUserName,
                (ConvertTo-SecureString -String $Node.AdministratorPassword -AsPlainText -Force)
            )
        }
    }
}

<#
    .SYNOPSIS
        Enforce members in a group.
#>
Configuration MSFT_ADGroup_EnforceMembersGroup5_Config
{
    Import-DscResource -ModuleName 'ActiveDirectoryDsc'

    node $AllNodes.NodeName
    {
        ADGroup 'Integration_Test'
        {
            GroupName  = $Node.Group5_Name
            Members    = @(
                'Administrator'
                'Guest'
            )

            Credential = New-Object `
                -TypeName System.Management.Automation.PSCredential `
                -ArgumentList @(
                $Node.AdministratorUserName,
                (ConvertTo-SecureString -String $Node.AdministratorPassword -AsPlainText -Force)
            )
        }
    }
}
```

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR refactors the module, unit and integration tests of the `ADGroup` resource as follows:

- Remove non mandatory parameters from `Get-TargetResource`.
- Remove nested `Try/Catch` blocks from `Get-TargetResource`.
- Refactor `Test-TargetResource` to use `Compare-ResourcePropertyState` common function.
- Refactor `Set-TargetResource` to use `Compare-ResourcePropertyState` common function.
- Modify membership add/Remove to use `Compare-Object` to only add/remove changed members.
- Fix `Set-ADCommonGroupMember` function so parameters are not changed.
- Fix `Credential` parameter description.
- Enhance integration tests to use a data driven pattern.
- Enhance unit tests to use contexts and newer standard test patterns.

#### This Pull Request (PR) fixes the following issues

- Fixes #494 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/631)

### CODE REVIEW

**Comment by davidwallis3101** [comment]
any further progress with this?

**Comment by johlju** [comment]
It is on my todo list to review.

**Review by johlju — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/631)* status: 4 of 11 files reviewed, all discussions resolved (waiting on @johlju)

___
*[source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1, line 103 at r3](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/631#-MQIT1VuDwod5HqYhWxg:-MQIT1VuDwod5HqYhWxh:b-wx74fk) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/b772025189f9ef09f8a48b92092c49f2fc498089/source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1#L103)):*
> ```
>             # This FullyQualifiedErrorId is indicative of a failure to retrieve members with Get-ADGroupMember
>             # for a one-way trust
> ```

We should use comment-block on comments that are more than one row. Throughout the code.

```powershell
<#
    This FullyQualifiedErrorId is indicative of a failure to retrieve members with Get-ADGroupMember
    for a one-way trust
#>
```
___
*[source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1, line 366 at r3](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/631#-MQISgGW9PwfEvT1AshH:-MQISOsy-R5K9XOpg4V8:b-prxvc) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/b772025189f9ef09f8a48b92092c49f2fc498089/source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1#L366)):*
> ```
>  [HashTable] $parameters = $PSBoundParameters
> ```

This does not really create a new hashtable? :thinking:  `[HashTable] $parameters = @{} + $PSBoundParameters` would. :thinking:

**Comment by johlju** [comment]
@X-Guardian I started the review but I is such a big change that I have not time to review it properly. You may merge this if you feel it is ready, and fix any problems after that.

If someone else have time to review the code fell free to do so.

**Pull request merged**
