### PR TITLE
ADDomain: Add DomainType support

### LINKED ISSUE #689: ADDomain: Add ability to specify DomainType to support TreeDomain use cases
### Problem description

To support use cases where a regional domain acts as a forest root domain (see [Selecting the Forest Root Domain](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/selecting-the-forest-root-domain) for more information) we need the ability to specify the DomainType separately.

### Verbose logs

```text
N/A
```

### DSC configuration

```powershell
N/A
```

### Suggested solution

We need the ability to specify the DomainType, for example:

```powershell
Configuration ADDomain_NewTreeDomain_Config
{
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [System.Management.Automation.PSCredential]
        $Credential,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [System.Management.Automation.PSCredential]
        $SafeModePassword
    )

    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName ActiveDirectoryDsc

    node 'localhost'
    {
        WindowsFeature 'ADDS'
        {
            Name   = 'AD-Domain-Services'
            Ensure = 'Present'
        }

        WindowsFeature 'RSAT'
        {
            Name   = 'RSAT-AD-PowerShell'
            Ensure = 'Present'
        }

        ADDomain 'child'
        {
            DomainName                    = 'branch.contoso.com'
            Credential                    = $Credential
            SafemodeAdministratorPassword = $SafeModePassword
            DomainMode                    = 'WinThreshold'
            ParentDomainName              = 'hq.contoso.com'
            DomainType                    = 'TreeDomain'
        }
    }
}
```

### Operating system the target node is running

```text
N/A
```

### PowerShell version and build the target node is running

```text
N/A
```

### ActiveDirectoryDsc version

```text
N/A
```

### LINKED ISSUE #692: Cannot create Tree domain with ADDomain Resource
### Problem description

Child domain works great, but I cannot create a tree in an existing forest with the ADDomain Resource

### Verbose logs

```text
PowerShell DSC resource MSFT_ADDomain  failed to execute Set-TargetResource functionality with error message: The 
running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
Verification of prerequisites for Domain Controller promotion failed. The child domain name "onpremisestree.local" has 
an invalid format. This name may contain letters, numbers, and hyphens, but not spaces or periods.
Characters that are not allowed include: ! " # $ % & ( ) * + , ' / : ; < = > ? @ [ \ ] ^ ` { | } ~
 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : LocalHost
```

### DSC configuration

```powershell
'TreeDomainController' {
  ADDomain PrimaryDC {
	  DomainName                    = $DomainDnsName
	  DomainNetBIOSName             = $DomainNetBIOSName
	  ParentDomainName              = $ParentDomainDNSName
	  Credential                    = $EaCredentials
	  SafemodeAdministratorPassword = $RestoreModeCredentials
	  DatabasePath                  = 'D:\NTDS'
	  LogPath                       = 'D:\NTDS'
	  SysvolPath                    = 'D:\SYSVOL'
	  DependsOn                     = '[User]AdministratorPassword'
  }
```

### Suggested solution

Add "TreeDomain" as an options to install a domain into an exiting resource

https://github.com/dsccommunity/ActiveDirectoryDsc/blob/main/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L477

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2022 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      5.1.20348.643
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.643
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### ActiveDirectoryDsc version

```text
Name               Version Path
----               ------- ----
ActiveDirectoryDsc 6.0.1   C:\Program Files\WindowsPowerShell\Modules\ActiveDirectoryDsc\6.0.1\ActiveDirectoryDsc.psd1
```

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

ADDomain resource: Add DomainType support

NB I'm not sure if this is completely correct but am having a go anyway! In particular I couldn't find a way to 'get' the current DomainType for a domain so Get-TargetResource should just return $null - is that OK?

#### This Pull Request (PR) fixes the following issues

- Fixes #689
- Fixes #692 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705)

### CODE REVIEW

**Comment by Borgquite** [comment]
How are the files under source/Examples/Resources/ADDomain generated? Those are missing at present because I don't know how to make the GUID.

**Comment by Borgquite** [comment]
@johlju OK - try it now :)

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1` line 129 at r1](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-NqYUD185EqqVlePJB-7:-NqYUD185EqqVlePJB-8:b-u9n2y5) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/1f415ae7f2a71ed6bf3ca47cca05b3cdb554d23f/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L129)):*
> ```PowerShell
>             DomainNetBiosName             = $domain.NetBIOSName
>             DnsDelegationCredential       = $null
>             DomainType                    = $null
> ```

It is okay to return `$null` here, but an another option is to also add the parameter to `Get-TargetResource` and return back the passed value. But good as-is.
___
*[`source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1` line 193 at r1](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-NqYV3xu2iZJ20ZgTJYL:-NqYV3xu2iZJ20ZgTJYM:bxz0pbm) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/1f415ae7f2a71ed6bf3ca47cca05b3cdb554d23f/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L193)):*
> ```PowerShell
>     .PARAMETER DomainType
>         Specifies whether the domain is a new domain tree in an existing forest ('TreeDomain'),
>         or a child of an existing domain ('ChildDomain'). Default value is 'ChildDomain'.
> ```

Suggest adding a sentence that says that the value is only used when creating the domain, it is not enforced. 

Throughout the comment-based, schema and documentation.
___
*[`source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1` line 501 at r1](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-NqYXcU9DK60zZ-sqKPQ:-NqYXcU9DK60zZ-sqKPR:bf7xkea) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/1f415ae7f2a71ed6bf3ca47cca05b3cdb554d23f/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L501)):*
> ```PowerShell
>             {
>                 $installADDSParameters['DomainType'] = $DomainType
>             }
> ```

I don't think we should use `ContainsKey()` here. Since you have a default value, and according how it was before this value should always be set (to the default value if not passed). Otherwise if you keep the code as is (since `Install-ADDSDomain` defaults to 'ChildDomain') then the default value should be removed from the parameters as it serves no purpose.



_Suggestion:_
```PowerShell
            $installADDSParameters['DomainType'] = $DomainType
```

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1` line 129 at r1](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-NqYUD185EqqVlePJB-7:-NqbGoJ3DZwfhctD96NF:b4b4pf6) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/1f415ae7f2a71ed6bf3ca47cca05b3cdb554d23f/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L129)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

It is okay to return `$null` here, but an another option is to also add the parameter to `Get-TargetResource` and return back the passed value. But good as-is.
</blockquote></details>

Done - I've put it into Get-TargetResource as suggested.
___
*[`source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1` line 193 at r1](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-NqYV3xu2iZJ20ZgTJYL:-NqbGjdvETuKW0KtMQae:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/1f415ae7f2a71ed6bf3ca47cca05b3cdb554d23f/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L193)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest adding a sentence that says that the value is only used when creating the domain, it is not enforced. 

Throughout the comment-based, schema and documentation.
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1` line 501 at r1](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-NqYXcU9DK60zZ-sqKPQ:-NqbGx5t3saXa068EBaA:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/1f415ae7f2a71ed6bf3ca47cca05b3cdb554d23f/source/DSCResources/MSFT_ADDomain/MSFT_ADDomain.psm1#L501)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I don't think we should use `ContainsKey()` here. Since you have a default value, and according how it was before this value should always be set (to the default value if not passed). Otherwise if you keep the code as is (since `Install-ADDSDomain` defaults to 'ChildDomain') then the default value should be removed from the parameters as it serves no purpose.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/705#-:-NqcrSgW9f55G0-vng6c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Pull request merged**
