### PR TITLE
ADOrganizationalUnit: Added DomainController Parameter #563

### LINKED ISSUE #563: ADOrganizationalUnit: Add DomainController parameter
### Description
The ADOrganizationUnit DSC resource has a 'Credential' parameter but does not have the 'DomainController' parameter. Therefore it is not possible to create an OU if the computer is not member of the domain.
The *-ADOrganizationalUnit CmdLets in the ActiveDirectory module all supports the 'Server' parameter so it should be possible to add this the 'DomainController' parameter to the resource.

### Proposed properties
DomainController: Specifies the Active Directory Domain Services instance to connect to perform the task.

### Special considerations or limitations
N/A

### PR DESCRIPTION
**Pull request by matt2005**
#### Pull Request (PR) description
Adds DomainController Parameter

#### This Pull Request (PR) fixes the following issues
- Fixes #563

#### Task list
- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666)

### CODE REVIEW

**Comment by johlju** [comment]
I updated the pipeline files from Sampler - so the pipeline works now. Please rebase this PR when you have a chance.

**Review by johlju — CHANGES_REQUESTED** [review]
Sorry it tooks so long to review this PR. Please rebase this PR to get the latest changes into this PR.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-:-N1-1dPC4WPv6O7R77B0:b-q8f1w2)* status: all files reviewed, 8 unresolved discussions (waiting on @matt2005)

___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 69 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-0m4sDWDp5Dmt-LyH:-N1-0m4sDWDp5Dmt-LyI:b-s1riji) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L69)):*
> ```PowerShell
>     Write-Verbose -Message ($script:localizedData.RetrievingOU -f $Name, $Path)
> 
>     $getADOUProperties = ('Name', 'DistinguishedName', 'Description', 'ProtectedFromAccidentalDeletion',
> ```

Why are we adding more properties here, e.g Name, ManagedBy and Info when they are not used below? We sould not retrieve properties we don't need?



_Code quote:_
```PowerShell
    $getADOUProperties = ('Name', 'DistinguishedName', 'Description', 'ProtectedFromAccidentalDeletion',
        'ManagedBy', 'Info')
```
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 79 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-1AwnCT7zdJqR_-Q-:-N1-1AwnCT7zdJqR_-Q0:b-31hupx) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L79)):*
> ```PowerShell
>         $getADOUParameters.Filter = ('Name -eq "{0}"' -f $Name)
>         $getADOUParameters.SearchBase = $Path
>         $getADOUParameters.Remove('Path')
> ```

Maybe we can group the removal of properties together so it easier to read?



_Code quote:_
```PowerShell
$getADOUParameters.Remove('Path')
```
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 81 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-1W1U3WHyh2TZc0aT:-N1-1W1U3WHyh2TZc0aU:b-aqet6g) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L81)):*
> ```PowerShell
>         $getADOUParameters.Remove('Path')
>         $getADOUParameters.SearchScope = 'OneLevel'
>         $getADOUParameters.Properties =$getADOUProperties
> ```

Missing space after equal sign.



_Code quote:_
```PowerShell
getADOUParameters.Properties =$getADOUProperties
```
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 82 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-1pPn7_EWdyu-MdA_:-N1-1pPn7_EWdyu-MdAa:b-8knycf) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L82)):*
> ```PowerShell
>         $getADOUParameters.SearchScope = 'OneLevel'
>         $getADOUParameters.Properties =$getADOUProperties
>         Write-Verbose -Message ($getADOUParameters | fl | out-string)
> ```

Is this meant to be here, or was it used during coding? If it meant to be there, them better to set this as  `Write-Debug` as it is not a descriptive verbose message.

Also it should be:



_Suggestion:_
```PowerShell
        Write-Verbose -Message ($getADOUParameters | Format-List| Out-String)
```
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 218 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-0Rkb63UGfg1TIIvY:-N1-0Rkb63UGfg1TIIvZ:b7cv2uv) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L218)):*
> ```PowerShell
>     @($getTargetResourceParameters.Keys) |
>         ForEach-Object {
>             if (-not $parameters.ContainsKey($_))
> ```

We can just use `$PSBoundParameters` here directly and skip the line that is setting `$parameters`above?



_Suggestion:_
```PowerShell
$PSBoundParameters
```
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 374 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-38zoD4JQfNBGtGa3:-N1-38zoD4JQfNBGtGa4:b7cv2uv) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L374)):*
> ```PowerShell
>     @($getTargetResourceParameters.Keys) |
>         ForEach-Object {
>             if (-not $parameters.ContainsKey($_))
> ```

We can just use `$PSBoundParameters` here directly and skip the line that is setting `$parameters`above?



_Suggestion:_
```PowerShell
$PSBoundParameters
```
___
*[`tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1` line 172 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-4OEv1bX3Zf3CHjo2:-N1-4OEv1bX3Zf3CHjo3:b-33uz5t) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1#L172)):*
> ```PowerShell
>                         -ParameterFilter { $ModuleName -eq 'ActiveDirectory' }
>                     Assert-MockCalled -CommandName Get-ADOrganizationalUnit `
>                         -ParameterFilter { $SearchBase -eq $getTargetResourceParameters.Path } `
> ```

Could verify here that the `Credential` property actually specified when calling the command?



_Code quote:_
```PowerShell
-ParameterFilter { $SearchBase -eq $getTargetResourceParameters.Path } `
```
___
*[`tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1` line 190 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-4CcX5r5IGbSIfYcj:-N1-4CcX5r5IGbSIfYck:bzggicn) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1#L190)):*
> ```PowerShell
>                         -ParameterFilter { $ModuleName -eq 'ActiveDirectory' }
>                     Assert-MockCalled -CommandName Get-ADOrganizationalUnit `
>                         -ParameterFilter { $SearchBase -eq $getTargetResourceParameters.Path } `
> ```

Could verify here that the `Server` parameter is actually specified when calling the command?



_Code quote:_
```PowerShell
-ParameterFilter { $SearchBase -eq $getTargetResourceParameters.Path } `
```

**Review by matt2005 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 69 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-0m4sDWDp5Dmt-LyH:-N1k0fIB0ypxQcY5NZt4:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L69)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why are we adding more properties here, e.g Name, ManagedBy and Info when they are not used below? We sould not retrieve properties we don't need?
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 79 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-1AwnCT7zdJqR_-Q-:-N1k0frNCkokttkAbUeE:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we can group the removal of properties together so it easier to read?
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 81 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-1W1U3WHyh2TZc0aT:-N1k0gjS2HrvVY_OCSwl:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Missing space after equal sign.
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 82 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-1pPn7_EWdyu-MdA_:-N1k0h40EcBifgC5S-81:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L82)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Is this meant to be here, or was it used during coding? If it meant to be there, them better to set this as  `Write-Debug` as it is not a descriptive verbose message.

Also it should be:
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 218 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-0Rkb63UGfg1TIIvY:-N1k0iHf1ttjpKXioOsD:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L218)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can just use `$PSBoundParameters` here directly and skip the line that is setting `$parameters`above?
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 374 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-38zoD4JQfNBGtGa3:-N1k0jisBxdKHMNfLHR9:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L374)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can just use `$PSBoundParameters` here directly and skip the line that is setting `$parameters`above?
</blockquote></details>

Done.
___
*[`tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1` line 172 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-4OEv1bX3Zf3CHjo2:-N1k0nRLE0sgDTw-Fnwe:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1#L172)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could verify here that the `Credential` property actually specified when calling the command?
</blockquote></details>

Done.
___
*[`tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1` line 190 at r2](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N1-4CcX5r5IGbSIfYcj:-N1k0ozn8AMduw2VrlFD:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/9e2cd2b915c8eeee90fa8524e377122490f9ccb8/tests/Unit/MSFT_ADOrganizationalUnit.Tests.ps1#L190)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could verify here that the `Server` parameter is actually specified when calling the command?
</blockquote></details>

Done.

**Review by johlju — CHANGES_REQUESTED** [review]
Great work on this, just two small changes then I think this is ready to be merged. :slightly_smiling_face:  

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-:-N223mdk9BdSUMFOTRTN:b-upww7z)* status: all files reviewed, 2 unresolved discussions (waiting on @matt2005)

___
*[`CHANGELOG.md` line 22 at r4](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N2239Pm63I5og7DKIw-:-N2239Pm63I5og7DKIw0:b-osog0d) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/0741f93111957f715dd5e639d6dcef313adeb3b4/CHANGELOG.md#L22)):*
> ```Markdown
>   - Refactored Unit and Integration Tests.
> 
> - ADOrganizationalUnit
> ```

We need to move this back up to the Unreleased section. When we do releases git doesn't understand that we shifted section name. :slightly_smiling_face: 



_Code quote:_
```Markdown
- ADOrganizationalUnit
  - Added DomainController Parameter.
```
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 205 at r4](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N221QMM3jESL_KTrnz4:-N221QMM3jESL_KTrnz5:b267zf7) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/0741f93111957f715dd5e639d6dcef313adeb3b4/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L205)):*
> ```PowerShell
> 
>     $getTargetResourceParameters = @{
>         Name             = $Name
> ```

Since Get only expects 4 parameters we should be able to simplify this to the following:

```powershell
    $getTargetResourceParameters = @{
        Name             = $Name
        Path             = $Path
        Credential       = $Credential
        DomainController = $DomainController
    }

    # Remove parameters that have not been specified.
    $getTargetResourceParameters.Keys |
        ForEach-Object {
            if (-not $PSBoundParameters.ContainsKey($_))
            {
                $getTargetResourceParameters.Remove($_)
            }
        }

    $getTargetResourceResult = Get-TargetResource @getTargetResourceParameters
```



_Suggestion:_
```PowerShell
    $getTargetResourceParameters = @{
        Name             = $Name
        Path             = $Path
        Credential       = $Credential
        DomainController = $DomainController
    }

    # Remove parameters that have not been specified.
    $getTargetResourceParameters.Keys |
        ForEach-Object {
            if (-not $PSBoundParameters.ContainsKey($_))
            {
                $getTargetResourceParameters.Remove($_)
            }
        }
```

**Review by matt2005 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`CHANGELOG.md` line 22 at r4](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N2239Pm63I5og7DKIw-:-N2pRrNG3Jd0N7fhnrec:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/0741f93111957f715dd5e639d6dcef313adeb3b4/CHANGELOG.md#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We need to move this back up to the Unreleased section. When we do releases git doesn't understand that we shifted section name. :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1` line 205 at r4](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N221QMM3jESL_KTrnz4:-N2pRqOrEaR5V1dm4bC9:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/0741f93111957f715dd5e639d6dcef313adeb3b4/source/DSCResources/MSFT_ADOrganizationalUnit/MSFT_ADOrganizationalUnit.psm1#L205)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Since Get only expects 4 parameters we should be able to simplify this to the following:

```powershell
    $getTargetResourceParameters = @{
        Name             = $Name
        Path             = $Path
        Credential       = $Credential
        DomainController = $DomainController
    }

    # Remove parameters that have not been specified.
    $getTargetResourceParameters.Keys |
        ForEach-Object {
            if (-not $PSBoundParameters.ContainsKey($_))
            {
                $getTargetResourceParameters.Remove($_)
            }
        }

    $getTargetResourceResult = Get-TargetResource @getTargetResourceParameters
```
</blockquote></details>

Done.

**Review by matt2005 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`CHANGELOG.md` line 42 at r6](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-N2w6o_f7DcCWpfMHRxK:-N3-0HBm1ZhwEv7WS9gm:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/146bf355fd478e8befcd84e403cec8f9699b81f5/CHANGELOG.md#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There is a duplicate entry here with the one in Unreleased section. It should be removed from here .
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/666#-:-N3-BSaQ9A2LQRQGBFmP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matt2005)

**Comment by johlju** [comment]
@matt2005 awesome! Thank you for this! 😄

**Pull request merged**
