### PR TITLE
ADManagedServiceAccount: Add CommonName parameter

### LINKED ISSUE #644: ADManagedServiceAccount: Add support for setting the SAM account name and (common) name separately
#### Details of the scenario you tried and the problem that is occurring
The ``ADManagedServiceAccount`` DSC resource configures Managed Service Accounts via the ``ServiceAccountName`` parameter only with the Security Account Manager (SAM) account name and the specified value is also applied to the (common) name of the object. When using the ``New-ADServiceAccount`` cmdlet you have to configure the SAM account name with it's 15 character limit but you can also configure the (common) name with a longer more friendly name. 

Example: 
```powershell
New-ADServiceAccount -Name "MyMoreFancyServiceLongName01" -SamAccountName "Service01" -DNSHostName "MyMoreFancyServiceLongName01.mydomain.com"
```
This results in a Managed Service Account with a distinguished name of ``CN=MyMoreFancyServiceLongName01,CN=Managed Service Accounts,DC=mydomain=DC=com`` instead of ``CN=Service01,CN=Managed Service Accounts,DC=mydomain=DC=com`` which is generated by the current DSC resource. Trying to use the longer name with the DSC task will result in a fault that indicates the length restriction regarding SAM account names.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Please add an option to specify the SAM account name and the name separately in the ADManagedServiceAccount DSC resource.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration ADManagedServiceAccount_CreateManagedServiceAccount_Config
{
    Import-DscResource -Module ActiveDirectoryDsc

    Node localhost
    {
        ADManagedServiceAccount 'ExampleStandaloneMSA'
        {
            Ensure = 'Present'
            ServiceAccountName = 'Service01'
            AccountType = 'Standalone'
        }
    }
}
```

#### The operating system the target node is running
Windows Server 2019

#### Version and build of PowerShell the target node is running
PSVersion: 5.1.17763.1490
PSEdition: Desktop
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0...}
BuildVersion: 10.0.17763.1490
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

#### Version of the DSC module that was used
6.0.1

### PR DESCRIPTION
**Pull request by Antiohne**
#### Pull Request (PR) description
Added support for setting a common name to a Managed Service Account for a longer more friendly name than    the SAM account name which has a 15 character limit.

#### This Pull Request (PR) fixes the following issues
- Fixes #644 

#### Task list

-  [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/661)

### CODE REVIEW

**Review by X-Guardian — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/661)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Antiohne)

*[a discussion](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/661#-MdlDjLP29-2xArry0We:-MdlDjLP29-2xArry0Wf:bgb56ds) (no related file):*
This PR needs integration tests.

Have you tested this change through the full lifecycle of an ADManagedServiceAccount object and this additional property? i.e. addition, modification and deletion of an ADManagedServiceAccount with and without this property, and addition, modification and deletion of this property. This must be a non-breaking change to current usage of this resource.

---

**Comment by Antiohne** [comment]
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/661)_ status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Antiohne)
> 
> _[a discussion](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/661#-MdlDjLP29-2xArry0We:-MdlDjLP29-2xArry0Wf:bgb56ds) (no related file):_
> This PR needs integration tests.
> 
> Have you tested this change through the full lifecycle of an ADManagedServiceAccount object and this additional property? i.e. addition, modification and deletion of an ADManagedServiceAccount with and without this property, and addition, modification and deletion of this property. This must be a non-breaking change to current usage of this resource.

Yes this change is non-breaking and is based on the ADUser im;plementation. If you do not specify a common name the common name of the Managed User Identity will be the same as the SamAccountName. When specified the common name will be different to the SamAccountName and the Distinguished Name will be based on the specified common name. 

The existing integration tests will now test that the value of the common name is the same as the SamAccountName. Additional tests are added for the creation and deletion of a managed service account with a common name. Another test will check the rename of that common name.

**Comment by Antiohne** [comment]
@X-Guardian : This change is ready for reviewing. The required integration tests are added and the full lifecycle is tested.

**Comment by Antiohne** [comment]
@X-Guardian : The requested integration tests are added in September. Is this PR now ready for review?

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/661#-:-N0zunuP3hou_-UwCoV9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @X-Guardian)

**Comment by johlju** [comment]
I push this through so we can iterate from here.

**Pull request merged**
