### PR TITLE
ADGroup: Updating means to retrieve group members

### LINKED ISSUE #616: ADGroup: Group Members From One-Way Trusted Domain Break Functionality
#### Details of the scenario you tried and the problem that is occurring
The scenario is that we have 2 domains "Domain A" and "Domain B" where a one-way trust is established so that it is outgoing from Domain A and incoming for Domain B. This setup ensures that users from Domain B are trusted by Domain A. If I am trying to manage AD groups in Domain A where any resources from Domain B have been set as members, the usage of the Get-ADGroupMember cmdlet in the ADGroup resource fails spectacularly in the strangest way.

#### Verbose logs showing the problem

```
The server was unable to process the request due to an internal error. 
For more information about the error, either turn on IncludeExceptionDetailInFaults
(either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send
the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation
and inspect the server trace logs.
```
#### Suggested solution to the issue
Instead of using the Get-ADGroupMember cmdlet we could do the following:

```powershell
(Get-ADGroup -Identity <GroupID> -Properties Members).Members | 
    ForEach-Object -Process { 
        Get-ADObject -Identity $_ -Properties SamAccountName, ObjectSID |
            Select-Object -Property distinguishedName, name, objectClass, objectGUID, SamAccountName, @{ Name = 'SID'; Expression = {$_.ObjectSID} }
    }
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```
ADGroup 'TestGroup'
{
            GroupName   = 'TestGroup'
            GroupScope  = 'DomainLocal'
            Category    = 'Security'
            Ensure      = 'Present'
            Path        = "CN=Users,DC=DomainB,DC=local"
            Description = 'Test Group Description'
}
```

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```
Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.17763.1007                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.17763.1007                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used

6.0.1

### PR DESCRIPTION
**Pull request by jeremyciak**
#### Pull Request (PR) description

This Pull Request is intended to offer a viable mechanism for the Get-TargetResource aspect of the ADGroup resource when dealing with group members through a one-way trust.

#### This Pull Request (PR) fixes the following issues

- Fixes #616 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/617)

### CODE REVIEW

**Comment by jeremyciak** [comment]
#616

**Comment by X-Guardian** [comment]
@jeremyciak, please continue the discussion on the issue thread, before you make any further additions to this PR.

**Comment by jeremyciak** [comment]
@X-Guardian, I apologize! I had a reply ready to comment on the issue thread and never actually hit the button to send it through. I have added that comment now.

**Comment by X-Guardian** [comment]
@jeremyciak, can you edit the PR description and add some detail and link to the issue.

**Comment by jeremyciak** [comment]
@X-Guardian I have added a description and link to the issue in the initial PR comment.

**Comment by X-Guardian** [comment]
Hi @jeremyciak, don't know if you have used 'Reviewable' before, but if you haven't, press the `Reviewable` button in the PR description to see all the review comments in the context of the code. You can the respond to each one individually there.

**Comment by X-Guardian** [comment]
___
*[source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1, line 237 at r6](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/617#-MBj7FgfEhajDI2_Kobu:-MBmMQKl02E2bZI_axR_:b-oqo08u) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/53f7c41969ebeb8e12c03fd0df2732d3461f5855/source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1#L237)):*
<details><summary><i>Previously, jeremyciak wrote…</i></summary><blockquote>

I haven't yet made any code changes to represent this request. I will do so once I get feedback on my comment. One question I have is at least if I am moving to `New-InvalidOperationException` away from `Write-Error` then should my syntax update be to change this:

```powershell
Write-Error -Exception $_.Exception
```

... to this:

```powershell
New-InvalidOperationException -ErrorRecord $_
```
</blockquote></details>

It just needs a generic message, something like 'Error retrieving membership for group. (ADG0014)'.

**Comment by X-Guardian** [comment]
This is getting pretty close @jeremyciak. I've tested your module updates in my lab and it is looking good. Just the last few review comments to cover.

For future info, when you have forked a GitHub repo, for each PR, create yourself a new branch on your fork for making any changes in, rather than using `master`. This makes it easier for reviewers to add your repo is a remote reference and check out the updated branch.

**Comment by jeremyciak** [comment]
Woohoo! Successful code coverage!

@X-Guardian, thank you so much for all of your time and effort spent guiding and educating me in all of this. I have learned a ton and I feel like a much more worthy contributor now.

**Comment by X-Guardian** [comment]
Regarding updating the `ActiveDirectoryDsc.Common` docs, you just need install the `platyps` module, change your path to the `source\Modules\ActiveDirectoryDsc.Common` folder and then run the `Build-Readme.ps1` script. If you get any errors, let me know what they are.

**Comment by X-Guardian** [comment]
@jeremyciak, can you try `Build-Readme.ps1`  with PowerShell 5.x rather than 7?

**Comment by X-Guardian** [comment]
OK @jeremyciak, looking good. My one-way trust tests work and I've just successfully run the ADGroup integration tests, so just the `ActiveDirectoryDsc.Common` docs update and we should be good to go!

**Comment by jeremyciak** [comment]
@X-Guardian, I just got the docs to successfully create and those changes are in the pipeline now. Seems like if you import the `platyPS` module first and then let the build mechanism do its thing then the `powershell-yaml` module does not have issue on Powershell 5.1. Probably something that warrants investigation at some point!

**Comment by briantist** [comment]
https://github.com/dsccommunity/ActiveDirectoryDsc/issues/235

**Pull request merged**
